artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/889a536b411b4d3f9885ab5b8557ad87/artifacts
end_time: 1725044192381
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 889a536b411b4d3f9885ab5b8557ad87
run_name: Default
run_uuid: 889a536b411b4d3f9885ab5b8557ad87
source_name: ''
source_type: 4
source_version: ''
start_time: 1725044192363
status: 3
tags: []
user_id: mle-user
